name: Test workflow for readme update

on:
  workflow_dispatch:

jobs:
  run_script:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.TEST_TOKEN }}

      - name: Run Python script
        run: python testScript.py

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Update README.md"

      - name: Push changes
        run: |
          git push origin develop
