name: Test Workflow for extracting changes

on:
  workflow_dispatch:
    inputs:
        test:
          type: string
          description: test description 1
          required: true

env:
  TEST_ENV1: test-evn1
  TEST_ENV2: test-evn2

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello
        run: echo "Hello, World!"
